#!/bin/bash

# Gather a list of sls files included in the merge request
slsfiles="$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | grep -E '\.sls$')"

# Test if any sls files have been modified in the merge request
# If there are, execute the linting type based on the argument that was passed
if grep -E '\.sls$' <<< "$slsfiles" &>/dev/null; then
    # Print which SLS files will be linted
    printf -- "-- $1 linting the following files --\n$slsfiles\n--\n"

    if [[ "$1" == 'jinja' ]]; then
        # jinja linting
        echo "$slsfiles" | xargs j2lint --ignore jinja-statements-indentation jinja-statements-delimiter operator-enclosed-by-spaces --extensions sls
    elif [[ "$1" == 'salt' ]]; then
        # salt linting
        echo "$slsfiles" | xargs salt-lint
    elif [[ "$1" == 'yaml' ]]; then
        # yaml linting
        # Adjust jinja templating before linting sls files or yamllint will throw errors
        #   jinja statements will have a comment character (#) placed in front of them
        #   jinja expressions will be replaced with the text 'jinja-expression-replaced'
        while read filename; do
            sed -i -E -e 's/(^\s*(\{%.*|(or|and)\s+(grains|pillar)\[.*|.*%\}).*\s*$)/# \1/g' -e 's/\{\{.*\}\}/jinja-expression-replaced/g' "$filename"
        done <<< $slsfiles
        
        # Evaluate sls files
        yamllint --strict $(while read filename; do printf "$filename "; done <<< "$slsfiles")
    else
       echo "The argument that was passed to the script did not match any linting types"
    fi
else
    echo "No sls files found, skipping $1 linting"
    exit 0
fi
